(()=>{"use strict";
const K="anywhere",K0="anywhereDocuments",K1="darkMode",D=180,$=id=>document.getElementById(id),u={s:$("s"),c:$("c"),l:$("l"),q:$("q"),o:$("logo")};
let s={v:2,t:0,d:[]},i=0,t=0,g=0;
const gid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,5),J=x=>{try{return x&&JSON.parse(x)}catch{return null}},doc=()=>s.d[i],notes=()=>doc()[2],save=n=>{clearTimeout(t);const w=()=>{try{localStorage.setItem(K,JSON.stringify(s))}catch{}};n?w():t=setTimeout(w,D)};
function load(){let x=J(localStorage.getItem(K));if(x&&x.v===2&&Array.isArray(x.d)&&x.d.length){s={v:2,t:x.t?1:0,d:x.d.map(d=>[d[0]||gid(),d[1]||"Untitled",Array.isArray(d[2])?d[2]:[]])};return}x=J(localStorage.getItem(K0))||{};const d=[];for(const k in x){const a=x[k]||{};d.push([a.id||k,a.title||"Untitled",Array.isArray(a.notes)?a.notes.map(n=>[n.x|0,n.y|0,n.html||n.text||""]):[]])}if(!d.length)d.push([gid(),"Untitled",[]]);d.sort((a,b)=>b[0].localeCompare(a[0]));s={v:2,t:localStorage.getItem(K1)==="true"?1:0,d};save(1);try{localStorage.removeItem(K0);localStorage.removeItem(K1)}catch{}}
function logo(){u.o.hidden=notes().length>0}
function draw(m,f){const n=document.createElement("div");n.className="n";n.contentEditable="true";n.spellcheck=false;n.style.left=m[0]+"px";n.style.top=m[1]+"px";n.innerHTML=m[2]||"";n._=m;u.c.appendChild(n);if(f)n.focus();return n}
function list(){const q=u.q.value.trim().toLowerCase();u.l.textContent="";s.d.forEach((d,n)=>{if(q&&!d[1].toLowerCase().includes(q))return;const r=document.createElement("div");r.className="i"+(n===i?" a":"");r.dataset.i=n;const p=document.createElement("span");p.className="t";p.textContent=d[1];const x=document.createElement("button");x.type="button";x.className="x";x.textContent="x";r.append(p,x);u.l.appendChild(r)})}
function title(){const n=u.c.querySelector(".n"),v=n?n.textContent.trim().slice(0,40):"",h=v||"Untitled";if(doc()[1]!==h){doc()[1]=h;list()}}
function open(n){if(n<0)n=0;if(n>=s.d.length)n=s.d.length-1;i=n;u.c.querySelectorAll(".n").forEach(e=>e.remove());notes().forEach(m=>draw(m,0));logo();list()}
function add(){s.d.unshift([gid(),"Untitled",[]]);open(0);save()}
function del(n){if(!confirm("Delete this document?"))return;s.d.splice(n,1);if(!s.d.length)s.d.push([gid(),"Untitled",[]]);if(n<i)i--;if(i>=s.d.length)i=s.d.length-1;open(i);save()}
function push(x,y){const m=[x|0,y|0,""];notes().push(m);draw(m,1);logo();title();save()}
function sync(n){n._[0]=parseInt(n.style.left,10)||0;n._[1]=parseInt(n.style.top,10)||0;n._[2]=n.innerHTML}
function drop(n){const a=notes(),p=a.indexOf(n._);if(p>-1)a.splice(p,1);n.remove();logo();title();save()}
function theme(){document.body.classList.toggle("d",!!s.t)}
function dragStart(e){const n=e.target.closest(".n");if(!n||e.button!==0)return;g={n,p:e.pointerId,x:e.clientX,y:e.clientY,l:parseInt(n.style.left,10)||0,t:parseInt(n.style.top,10)||0,m:0};n.setPointerCapture(e.pointerId)}
function dragMove(e){if(!g||e.pointerId!==g.p)return;const x=e.clientX-g.x,y=e.clientY-g.y;if(!g.m&&Math.abs(x)+Math.abs(y)>6){g.m=1;g.n.contentEditable="false";g.n.classList.add("g")}if(g.m){g.n.style.left=g.l+x+"px";g.n.style.top=g.t+y+"px";sync(g.n)}}
function dragEnd(e){if(!g||e.pointerId!==g.p)return;if(g.m){g.n.contentEditable="true";g.n.classList.remove("g");save()}g=0}
function events(){u.s.addEventListener("click",e=>{const b=e.target.closest("[data-a]");if(!b)return;const a=b.dataset.a;if(a==="toggle")u.s.classList.toggle("c");else if(a==="new")add();else if(a==="search"){u.q.hidden=!u.q.hidden;if(u.q.hidden){u.q.value="";list()}else u.q.focus()}else if(a==="theme"){s.t=s.t?0:1;theme();save()}});u.q.addEventListener("input",list);u.l.addEventListener("click",e=>{const r=e.target.closest(".i");if(!r)return;const n=+r.dataset.i;e.target.closest(".x")?del(n):open(n)});u.c.addEventListener("click",e=>{if(e.target!==u.c)return;const r=u.c.getBoundingClientRect();push(e.clientX-r.left,e.clientY-r.top)});u.c.addEventListener("input",e=>{const n=e.target.closest(".n");if(!n)return;sync(n);title();save()});u.c.addEventListener("focusout",e=>{const n=e.target.closest(".n");if(n&&!n.textContent.trim()&&!n.querySelector("img"))drop(n)});u.c.addEventListener("keydown",e=>{const n=e.target.closest(".n");if(!n||!(e.metaKey||e.ctrlKey))return;const k=e.key.toLowerCase();if(k!=="b"&&k!=="i")return;e.preventDefault();document.execCommand(k==="b"?"bold":"italic");sync(n);title();save()});u.c.addEventListener("pointerdown",dragStart);u.c.addEventListener("pointermove",dragMove);u.c.addEventListener("pointerup",dragEnd);u.c.addEventListener("pointercancel",dragEnd)}
function init(){load();theme();open(0);events()}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
